# docker-compose.yml
services:
  postgres:
    image: postgres:16-alpine
    container_name: credit_review_db
    environment:
      POSTGRES_USER: credit_user
      POSTGRES_PASSWORD: credit_pass_dev
      POSTGRES_DB: credit_review
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U credit_user -d credit_review"]
      interval: 5s
      retries: 5

volumes:
  postgres_data: